Repository SrijanShovit/HealthLearning, pull requests merged in 2024-05, with the labels that each got.

#23 Metabolic Syndrome Prediction: Dataset Exploration issue #5
  Metabolic Syndrome Prediction/metabolic_syndrome_predict.ipynb
Labels: gssoc, level1

#24 Add PCA analysis and variance explained ratio plots
  Body Fat Prediction/BodyFatPCA.ipynb
  Body Fat Prediction/PCA_description.md
Labels: gssoc24, gssoc, level1

#39 Metabolic Syndrome Prediction | 2. EDA
  Metabolic Syndrome Prediction/metabolic_syndrome_predict.ipynb
Labels: gssoc24, gssoc, level2, level 2

#32 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc24, gssoc, level 1, level1

#34 Diabetes Classification | 1. Dataset Exploration
  Diabetes Classification/diabetesclassification.ipynb
Labels: gssoc24, gssoc, level 1, level1

#29 Step 1
  Cirrhosis Prediction/Cirrhosis_Prediction.ipynb
Labels: gssoc24, gssoc, level 1, level1

#35 Cardiovascular Heart Disease Prediction | 1. Dataset Exploration
  Cardiovascular Heart Disease/Data_Exploration.ipynb
  Cardiovascular Heart Disease/heart_data.csv
Labels: gssoc24, gssoc, level 1, level1

#46 Breast Cancer Prediction | 1. Dataset Exploration
  Breast Cancer Prediction/Breast Cancer Prediction.ipynb
  Breast Cancer Prediction/README.md
Labels: gssoc24, gssoc, level 1, level1

#40 StrokePrediction|ExploreDataset
  Stroke Prediction/StrokePrediction-ExploreDataset.ipynb
Labels: gssoc24, gssoc, level 1, level1

#37 Added Dataset Exploration part and renamed the file
  Body Fat Prediction/BodyFatPCA.ipynb
  Body Fat Prediction/BodyFatPrediction.ipynb
  Body Fat Prediction/bodyfat.csv
Labels: gssoc24, gssoc, level 1, level1

#55 Added Issue Template and Pull Request Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/feauture_addition.md
  .github/workflows/pull_request_template.md
Labels: gssoc24, gssoc, level 1, level1

#64 PCOS_DATASET_EXPLORATION
  PCOS/PCOS_DATASET_EXPLORATION.ipynb
  PCOS/PCOS_data.csv
Labels: gssoc24, gssoc, level 1, level1

#33 Add feature importance analysis using Chi-squared and ANOVA tests
  Body Fat Prediction/Feature_importance.md
  Body Fat Prediction/Feature_importance_analysis.ipynb
Labels: gssoc24, gssoc, level 1, level1

#59 Outlier Detection
  Body Fat Prediction/BodyFatPrediction.ipynb
Labels: gssoc24, gssoc, level 1, level1

#43 Infant Health Prediction | Explore Dataset
  Infant Health Prediction/Synthetic-Infant-Health-Data.csv
  Infant Health Prediction/synthetic-infant-health-dataset-explore-dataset.ipynb
Labels: gssoc24, gssoc, level 1, level1

#69 feat: automate greetings using github bot
  .github/workflows/greetings.yml
Labels: gssoc24, gssoc, level 1, level1

#63 EDA FOR BREAST CANCER PREDICTION
  Breast Cancer Prediction/Breast Cancer Prediction (2).ipynb
  Breast Cancer Prediction/Breast Cancer Prediction.ipynb
Labels: gssoc24, gssoc, level 1, level1

#61 Metabolic Syndrome Prediction | 3. Statistical Tests for Feature Importance
  Metabolic Syndrome Prediction/metabolic_syndrome_predict.ipynb
Labels: gssoc24, gssoc, level 1, level1

#82 added EDA
  Stroke Prediction/StrokePrediction-EDA.ipynb
Labels: gssoc24, gssoc, level 1, level1

#81 Fixes issue#45
  Lung Cancer Detection/Lung_Cancer_Detection_EDA.ipynb
Labels: gssoc24, gssoc, level 1, level1

#71 Add new file of Lung Cancer Dataset Exploration
  Lung Cancer Detection/Lung-cancer-detection-Exploration.ipynb
  Lung-cancer-detection-Exploration.ipynb
Labels: gssoc24, gssoc, level 1, level1

#90 Cardiovascular Heart Disease Prediction | 2. EDA
  Cardiovascular Heart Disease/Data_Exploration.ipynb
  Cardiovascular Heart Disease/Data_Exploration_EDA.ipynb
Labels: gssoc24, gssoc, level 1, level1

#92 Metabolic Syndrome Prediction | 4. ML-based Feature Importance
  Metabolic Syndrome Prediction/metabolic_syndrome_predict.ipynb
Labels: gssoc24, gssoc, level 1, level1

#94 added csv and dataset exploration file
  Maternal Health Risk Prediction/Maternal Health Risk Data Set.csv
  Maternal Health Risk Prediction/Maternal_health_risk_prediction_dataset_exploration.ipynb
Labels: gssoc24, gssoc, level 1, level1

#70 Added comparison of feature importance scores from different algorithms
  Body Fat Prediction/Feature_Importance_score.ipynb
Labels: gssoc24, gssoc, level 1, level1

#112 added workflow for closing old issues
  .github/workflows/close-old-issue.yml
Labels: gssoc24, gssoc, level 1, level1

#117 Hepatitis C Prediction | Dataset Exploration #26
  Hepatitis C Prediction/Hepatitis C Prediction.ipynb
Labels: gssoc24, gssoc, level1

#111 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: gssoc24, gssoc, level 1, level1

#126 Due to the name change of the file Maternal Health Risk prediction
  Maternal Health Risk Prediction/Maternal_health_risk_prediction_EDA.ipynb.ipynb
Labels: gssoc24, gssoc, level 1, level1
